# Generated by Django 6.0.5 on 2026-07-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_department_projecttype_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailytask",
            options={
                "ordering": ["-task_date", "-created_at"],
                "permissions": [("manage_daily_tasks", "Can fully manage daily tasks")],
                "verbose_name": "Daily Task",
                "verbose_name_plural": "Daily Tasks",
            },
        ),
    ]
