# Generated by Django 6.0.5 on 2026-07-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_alter_dailytask_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailytask",
            options={
                "ordering": ["-task_date", "-created_at"],
                "verbose_name": "Daily Task",
                "verbose_name_plural": "Daily Tasks",
            },
        ),
    ]
