# Generated by Django 6.0.5 on 2026-09-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_alter_task_description_alter_task_due_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="department",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_manager",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_type",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team_members",
        ),
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projecthistory",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projecthistory",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AddField(
            model_name="task",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_tasks",
                to="tasks.brand",
            ),
        ),
        migrations.DeleteModel(
            name="DailyTask",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="ProjectType",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectHistory",
        ),
    ]
