# Generated by Django 6.0.5 on 2026-09-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_remove_project_department_remove_project_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingWith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Task Pending With",
                "verbose_name_plural": "Task Pending With",
            },
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Priority",
                "verbose_name_plural": "Priorities",
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="pending_with",
        ),
        migrations.RemoveField(
            model_name="task",
            name="priority",
        ),
        migrations.AddField(
            model_name="task",
            name="model_pending_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.pendingwith",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="model_priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.priority",
            ),
        ),
    ]
