# Generated by Django 6.0.5 on 2026-09-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_pendingwith_priority_remove_task_pending_with_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="model_pending_with",
            new_name="pending_with",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="model_priority",
            new_name="priority",
        ),
    ]
