# Generated by Django 6.0.5 on 2026-09-07 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_rename_model_pending_with_task_pending_with_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("sender", models.EmailField(max_length=254)),
                (
                    "recipients",
                    models.TextField(
                        blank=True, help_text="Comma separated email addresses"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="TaskEmailReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_date", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="tasks.taskemail",
                    ),
                ),
            ],
            options={
                "ordering": ("-reminder_date",),
            },
        ),
    ]
