# Generated by Django 6.0.5 on 2026-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_taskemail_taskemailreminder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskemail",
            options={},
        ),
        migrations.RemoveField(
            model_name="taskemail",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="taskemail",
            name="received_at",
        ),
        migrations.RemoveField(
            model_name="taskemail",
            name="recipients",
        ),
        migrations.RemoveField(
            model_name="taskemail",
            name="sender",
        ),
        migrations.AlterField(
            model_name="taskemail",
            name="sent_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
