# Generated by Django 6.0.5 on 2026-09-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_alter_taskemail_options_remove_taskemail_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskActionStep",
        ),
    ]
