# Generated by Django 6.0.5 on 2026-09-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_delete_taskactionstep"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="priority",
            options={
                "ordering": ("sort_order",),
                "verbose_name": "Priority",
                "verbose_name_plural": "Priorities",
            },
        ),
        migrations.AddField(
            model_name="priority",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
