# Generated by Django 6.0.5 on 2026-09-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0024_alter_priority_options_priority_sort_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskEmailReminder",
        ),
    ]
