# Generated by Django 6.0.5 on 2026-09-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0025_delete_taskemailreminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortTaskReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Short Task Reminder",
                "verbose_name_plural": "Short Task Reminders",
                "ordering": ("is_done", "-created_at"),
            },
        ),
    ]
