# Generated by Django 6.0.5 on 2026-09-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0026_shorttaskreminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskemail",
            name="sent_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
