# Generated by Django 6.0.5 on 2026-09-08 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscriptiontracker_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcard",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="subscriptiontracker",
            name="last_debit_processed_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="CardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        default="debit",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="subscriptions.paymentcard",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_transactions",
                        to="subscriptions.subscriptiontracker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Transaction",
                "verbose_name_plural": "Card Transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
