# Generated by Django 6.0.5 on 2026-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_paymentcard_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontracker",
            name="platform",
            field=models.CharField(max_length=150),
        ),
    ]
