# Generated by Django 6.0.5 on 2026-09-26 19:43

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models

import ticket_mail.models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_mail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedEmailDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("domain",),
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_index", models.PositiveIntegerField()),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url=None,
                            location="D:\\Projects\\Python\\Django\\deepsea_tasks\\private_ticket_files",
                        ),
                        upload_to=ticket_mail.models.attachment_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ticket_mail.ticketemailmessage",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ticket_mail.supportticket",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "part_index"),
                        name="unique_ticket_mail_attachment_part",
                    )
                ],
            },
        ),
    ]
