# Generated by Django 6.0.5 on 2026-09-26 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_mail", "0002_allowedemaildomain_ticketattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailboxSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
