# Generated by Django 6.0.5 on 2026-09-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_mail", "0003_mailboxsyncstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailboxsyncstate",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
