# Generated by Django 6.0.5 on 2026-09-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_mail", "0004_mailboxsyncstate_last_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketattachment",
            name="content_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="is_inline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticketemailmessage",
            name="html_body",
            field=models.TextField(blank=True),
        ),
    ]
