# Generated by Django 6.0.5 on 2026-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tutorialstep",
            name="unique_tutorial_step_position",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="introduction",
        ),
        migrations.AddField(
            model_name="tutorial",
            name="content",
            field=models.TextField(
                blank=True, help_text="Paste the complete tutorial in Markdown format."
            ),
        ),
        migrations.DeleteModel(
            name="TutorialStep",
        ),
    ]
