# Generated by Django 6.0.5 on 2026-09-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_supporttickethistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="expected_deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
