# Generated by Django 6.0.5 on 2026-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_supportticket_expected_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="marked_for_review",
            field=models.BooleanField(default=False),
        ),
    ]
