# Generated by Django 6.0.5 on 2026-09-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_supportticket_marked_for_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="quote_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
