# Generated by Django 6.0.5 on 2026-09-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("ticket", "Ticket"),
                            ("task", "Task"),
                            ("subscription", "Subscription"),
                            ("domain", "Domain"),
                            ("approval", "Approval"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Internal page path to open when clicked.",
                        max_length=500,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="notificatio_is_read_1cb71a_idx",
                    )
                ],
            },
        ),
    ]
