# Generated by Django 6.0.5 on 2026-09-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_shorttaskreminder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shorttaskreminder",
            options={
                "ordering": ("is_done", "-created_at"),
                "verbose_name": "Short Task Reminder",
                "verbose_name_plural": "Short Task Reminders",
            },
        ),
        migrations.RemoveField(
            model_name="shorttaskreminder",
            name="remind_at",
        ),
    ]
