# Generated by Django 6.0.5 on 2026-09-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_shorttaskreminder_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShortTaskReminder",
        ),
    ]
